from collections.abc import Iterator
from typing import Any, TypeAlias

Vec2: TypeAlias = tuple[float, float]
Vec3: TypeAlias = tuple[float, float, float]
Vec4: TypeAlias = tuple[float, float, float, float]
Matrix4: TypeAlias = tuple[Vec4, Vec4, Vec4, Vec4]
Transform: TypeAlias = dict[str, Vec3 | Vec4]
MaterialMap: TypeAlias = dict[str, Any]
ReadableBuffer: TypeAlias = bytes | bytearray | memoryview

__ufbx_version__: tuple[int, int, int]
__thread_safe__: bool


class Property:
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def value(self) -> bool | int | float | str | bytes | Vec3 | Vec4 | None: ...
    @property
    def is_user_defined(self) -> bool: ...
    @property
    def is_animatable(self) -> bool: ...


class Camera:
    @property
    def name(self) -> str: ...
    @property
    def projection(self) -> str: ...
    @property
    def resolution(self) -> Vec2: ...
    @property
    def field_of_view(self) -> Vec2: ...
    @property
    def orthographic_size(self) -> Vec2: ...
    @property
    def aspect_ratio(self) -> float: ...
    @property
    def near_plane(self) -> float: ...
    @property
    def far_plane(self) -> float: ...
    @property
    def focal_length_mm(self) -> float: ...
    @property
    def properties(self) -> tuple[Property, ...]: ...
    def find_property(self, name: str) -> Property | None: ...


class Light:
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def color(self) -> Vec3: ...
    @property
    def intensity(self) -> float: ...
    @property
    def local_direction(self) -> Vec3: ...
    @property
    def inner_angle(self) -> float: ...
    @property
    def outer_angle(self) -> float: ...
    @property
    def casts_shadows(self) -> bool: ...
    @property
    def properties(self) -> tuple[Property, ...]: ...


class Bone:
    @property
    def name(self) -> str: ...
    @property
    def radius(self) -> float: ...
    @property
    def relative_length(self) -> float: ...
    @property
    def is_root(self) -> bool: ...
    @property
    def properties(self) -> tuple[Property, ...]: ...


class Element:
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def element_id(self) -> int: ...
    @property
    def typed_id(self) -> int: ...
    @property
    def instances(self) -> tuple[Node, ...]: ...
    @property
    def properties(self) -> tuple[Property, ...]: ...
    @property
    def connections_from(self) -> tuple[dict[str, Any], ...]: ...
    @property
    def connections_to(self) -> tuple[dict[str, Any], ...]: ...
    def find_property(self, name: str) -> Property | None: ...


class NurbsCurve:
    @property
    def name(self) -> str: ...
    @property
    def basis(self) -> dict[str, Any]: ...
    @property
    def control_points(self) -> tuple[Vec4, ...]: ...
    def evaluate(self, parameter: float) -> dict[str, Any]: ...


class NurbsSurface:
    @property
    def name(self) -> str: ...
    @property
    def basis_u(self) -> dict[str, Any]: ...
    @property
    def basis_v(self) -> dict[str, Any]: ...
    @property
    def control_point_dimensions(self) -> tuple[int, int]: ...
    @property
    def control_points(self) -> tuple[Vec4, ...]: ...
    @property
    def flip_normals(self) -> bool: ...
    def evaluate(self, u: float, v: float) -> dict[str, Any]: ...


class SkinCluster:
    @property
    def name(self) -> str: ...
    @property
    def bone(self) -> Node | None: ...
    @property
    def geometry_to_bone(self) -> Matrix4: ...
    @property
    def weights(self) -> tuple[tuple[int, float], ...]: ...


class SkinDeformer:
    @property
    def name(self) -> str: ...
    @property
    def clusters(self) -> tuple[SkinCluster, ...]: ...
    @property
    def num_vertices(self) -> int: ...
    @property
    def max_weights_per_vertex(self) -> int: ...
    def weights(self, vertex_index: int) -> tuple[dict[str, Any], ...]: ...


class BlendShape:
    @property
    def name(self) -> str: ...
    @property
    def num_offsets(self) -> int: ...
    @property
    def offsets(self) -> tuple[dict[str, Any], ...]: ...


class BlendChannel:
    @property
    def name(self) -> str: ...
    @property
    def weight(self) -> float: ...
    @property
    def keyframes(self) -> tuple[dict[str, Any], ...]: ...


class BlendDeformer:
    @property
    def name(self) -> str: ...
    @property
    def channels(self) -> tuple[BlendChannel, ...]: ...


class Texture:
    @property
    def name(self) -> str: ...
    @property
    def filename(self) -> str: ...
    @property
    def relative_filename(self) -> str: ...
    @property
    def uv_set(self) -> str: ...
    @property
    def embedded_content(self) -> bytes | None: ...


class Material:
    @property
    def name(self) -> str: ...
    @property
    def element_id(self) -> int: ...
    @property
    def shading_model(self) -> str: ...
    @property
    def shader_type(self) -> int: ...
    @property
    def pbr(self) -> dict[str, MaterialMap]: ...
    @property
    def fbx(self) -> dict[str, MaterialMap]: ...
    @property
    def textures(self) -> tuple[Texture, ...]: ...
    @property
    def properties(self) -> tuple[Property, ...]: ...
    def find_property(self, name: str) -> Property | None: ...


class Mesh:
    @property
    def name(self) -> str: ...
    @property
    def element_id(self) -> int: ...
    @property
    def num_vertices(self) -> int: ...
    @property
    def num_indices(self) -> int: ...
    @property
    def num_faces(self) -> int: ...
    @property
    def num_triangles(self) -> int: ...
    @property
    def vertices(self) -> tuple[Vec3, ...]: ...
    @property
    def vertex_positions(self) -> tuple[Vec3, ...]: ...
    @property
    def normals(self) -> tuple[Vec3, ...] | None: ...
    @property
    def uvs(self) -> tuple[Vec2, ...] | None: ...
    @property
    def colors(self) -> tuple[Vec4, ...] | None: ...
    @property
    def faces(self) -> tuple[tuple[int, ...], ...]: ...
    @property
    def edges(self) -> tuple[tuple[int, int], ...]: ...
    @property
    def topology(self) -> tuple[dict[str, Any], ...]: ...
    @property
    def triangles(self) -> tuple[tuple[int, int, int], ...]: ...
    @property
    def triangle_indices(self) -> tuple[tuple[int, int, int], ...]: ...
    @property
    def face_material_indices(self) -> tuple[int, ...] | None: ...
    @property
    def materials(self) -> tuple[Material, ...]: ...
    @property
    def instances(self) -> tuple[Node, ...]: ...
    @property
    def skin_deformers(self) -> tuple[SkinDeformer, ...]: ...
    @property
    def blend_deformers(self) -> tuple[BlendDeformer, ...]: ...
    @property
    def generated_normals(self) -> bool: ...
    @property
    def subdivision(self) -> dict[str, Any]: ...
    def weighted_face_normal(self, face_index: int) -> Vec3: ...
    @property
    def properties(self) -> tuple[Property, ...]: ...
    def find_property(self, name: str) -> Property | None: ...


class AnimationStack:
    @property
    def name(self) -> str: ...
    @property
    def time_begin(self) -> float: ...
    @property
    def time_end(self) -> float: ...
    @property
    def duration(self) -> float: ...
    @property
    def layers(self) -> tuple[AnimationLayer, ...]: ...


class AnimationCurve:
    @property
    def name(self) -> str: ...
    @property
    def keyframes(self) -> tuple[dict[str, Any], ...]: ...
    @property
    def time_range(self) -> tuple[float, float]: ...
    @property
    def value_range(self) -> tuple[float, float]: ...
    def evaluate(self, time: float, fallback: float = 0.0) -> float: ...


class AnimationLayer:
    @property
    def name(self) -> str: ...
    @property
    def weight(self) -> float: ...
    @property
    def additive(self) -> bool: ...
    @property
    def curves(self) -> tuple[AnimationCurve, ...]: ...


class Node:
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def element_id(self) -> int: ...
    @property
    def attribute_type(self) -> str: ...
    @property
    def parent(self) -> Node | None: ...
    @property
    def children(self) -> tuple[Node, ...]: ...
    @property
    def mesh(self) -> Mesh | None: ...
    @property
    def camera(self) -> Camera | None: ...
    @property
    def light(self) -> Light | None: ...
    @property
    def bone(self) -> Bone | None: ...
    @property
    def attribute(self) -> Element | None: ...
    @property
    def materials(self) -> tuple[Material, ...]: ...
    @property
    def visible(self) -> bool: ...
    @property
    def is_root(self) -> bool: ...
    @property
    def local_transform(self) -> Transform: ...
    @property
    def geometry_transform(self) -> Transform: ...
    @property
    def node_to_world(self) -> Matrix4: ...
    @property
    def geometry_to_world(self) -> Matrix4: ...
    @property
    def properties(self) -> tuple[Property, ...]: ...
    def find_property(self, name: str) -> Property | None: ...
    def find(self, name: str) -> Node | None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Node]: ...


class Scene:
    @property
    def root(self) -> Node: ...
    @property
    def nodes(self) -> tuple[Node, ...]: ...
    @property
    def meshes(self) -> tuple[Mesh, ...]: ...
    @property
    def materials(self) -> tuple[Material, ...]: ...
    @property
    def textures(self) -> tuple[Texture, ...]: ...
    @property
    def animations(self) -> tuple[AnimationStack, ...]: ...
    @property
    def animation_curves(self) -> tuple[AnimationCurve, ...]: ...
    @property
    def cameras(self) -> tuple[Camera, ...]: ...
    @property
    def lights(self) -> tuple[Light, ...]: ...
    @property
    def bones(self) -> tuple[Bone, ...]: ...
    @property
    def elements(self) -> tuple[Element, ...]: ...
    @property
    def nurbs_curves(self) -> tuple[NurbsCurve, ...]: ...
    @property
    def nurbs_surfaces(self) -> tuple[NurbsSurface, ...]: ...
    def elements_of_type(self, type: str) -> tuple[Element, ...]: ...
    @property
    def warnings(self) -> tuple[dict[str, Any], ...]: ...
    @property
    def filename(self) -> str: ...
    @property
    def creator(self) -> str: ...
    @property
    def file_format(self) -> str: ...
    @property
    def file_version(self) -> int: ...
    @property
    def is_ascii(self) -> bool: ...
    @property
    def unit_meters(self) -> float: ...
    @property
    def frames_per_second(self) -> float: ...
    @property
    def memory_used(self) -> int: ...
    def find_node(self, name: str) -> Node | None: ...
    def evaluate(
        self,
        time: float,
        animation: AnimationStack | None = None,
        evaluate_skinning: bool = True,
    ) -> Scene: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __getitem__(self, key: int | str) -> Node: ...


def load(filename: str, options: dict[str, object]) -> Scene: ...
def loads(data: ReadableBuffer, filename: str, options: dict[str, object]) -> Scene: ...
