from collections.abc import Iterator
from typing import Any, TypeAlias

Vec2: TypeAlias = tuple[float, float]
Vec3: TypeAlias = tuple[float, float, float]
Vec4: TypeAlias = tuple[float, float, float, float]
Matrix4: TypeAlias = tuple[Vec4, Vec4, Vec4, Vec4]
Transform: TypeAlias = dict[str, Vec3 | Vec4]
MaterialMap: TypeAlias = dict[str, Any]
ReadableBuffer: TypeAlias = bytes | bytearray | memoryview

__ufbx_version__: tuple[int, int, int]
__thread_safe__: bool


class LoadError(RuntimeError): ...


class Texture:
    @property
    def name(self) -> str: ...
    @property
    def filename(self) -> str: ...
    @property
    def relative_filename(self) -> str: ...
    @property
    def uv_set(self) -> str: ...
    @property
    def embedded_content(self) -> bytes | None: ...


class Material:
    @property
    def name(self) -> str: ...
    @property
    def element_id(self) -> int: ...
    @property
    def shading_model(self) -> str: ...
    @property
    def shader_type(self) -> int: ...
    @property
    def pbr(self) -> dict[str, MaterialMap]: ...
    @property
    def fbx(self) -> dict[str, MaterialMap]: ...
    @property
    def textures(self) -> tuple[Texture, ...]: ...


class Mesh:
    @property
    def name(self) -> str: ...
    @property
    def element_id(self) -> int: ...
    @property
    def num_vertices(self) -> int: ...
    @property
    def num_indices(self) -> int: ...
    @property
    def num_faces(self) -> int: ...
    @property
    def num_triangles(self) -> int: ...
    @property
    def vertices(self) -> tuple[Vec3, ...]: ...
    @property
    def vertex_positions(self) -> tuple[Vec3, ...]: ...
    @property
    def normals(self) -> tuple[Vec3, ...] | None: ...
    @property
    def uvs(self) -> tuple[Vec2, ...] | None: ...
    @property
    def colors(self) -> tuple[Vec4, ...] | None: ...
    @property
    def faces(self) -> tuple[tuple[int, ...], ...]: ...
    @property
    def triangles(self) -> tuple[tuple[int, int, int], ...]: ...
    @property
    def triangle_indices(self) -> tuple[tuple[int, int, int], ...]: ...
    @property
    def face_material_indices(self) -> tuple[int, ...] | None: ...
    @property
    def materials(self) -> tuple[Material, ...]: ...
    @property
    def instances(self) -> tuple[Node, ...]: ...
    @property
    def generated_normals(self) -> bool: ...


class AnimationStack:
    @property
    def name(self) -> str: ...
    @property
    def time_begin(self) -> float: ...
    @property
    def time_end(self) -> float: ...
    @property
    def duration(self) -> float: ...


class Node:
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def element_id(self) -> int: ...
    @property
    def attribute_type(self) -> str: ...
    @property
    def parent(self) -> Node | None: ...
    @property
    def children(self) -> tuple[Node, ...]: ...
    @property
    def mesh(self) -> Mesh | None: ...
    @property
    def materials(self) -> tuple[Material, ...]: ...
    @property
    def visible(self) -> bool: ...
    @property
    def is_root(self) -> bool: ...
    @property
    def local_transform(self) -> Transform: ...
    @property
    def geometry_transform(self) -> Transform: ...
    @property
    def node_to_world(self) -> Matrix4: ...
    @property
    def geometry_to_world(self) -> Matrix4: ...
    def find(self, name: str) -> Node | None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Node]: ...


class Scene:
    @property
    def root(self) -> Node: ...
    @property
    def nodes(self) -> tuple[Node, ...]: ...
    @property
    def meshes(self) -> tuple[Mesh, ...]: ...
    @property
    def materials(self) -> tuple[Material, ...]: ...
    @property
    def textures(self) -> tuple[Texture, ...]: ...
    @property
    def animations(self) -> tuple[AnimationStack, ...]: ...
    @property
    def warnings(self) -> tuple[dict[str, Any], ...]: ...
    @property
    def filename(self) -> str: ...
    @property
    def creator(self) -> str: ...
    @property
    def file_format(self) -> str: ...
    @property
    def file_version(self) -> int: ...
    @property
    def is_ascii(self) -> bool: ...
    @property
    def unit_meters(self) -> float: ...
    @property
    def frames_per_second(self) -> float: ...
    @property
    def memory_used(self) -> int: ...
    def find_node(self, name: str) -> Node | None: ...
    def evaluate(
        self,
        time: float,
        animation: AnimationStack | None = None,
        evaluate_skinning: bool = True,
    ) -> Scene: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __getitem__(self, key: int | str) -> Node: ...


def load(filename: str, options: dict[str, object]) -> Scene: ...
def loads(data: ReadableBuffer, filename: str, options: dict[str, object]) -> Scene: ...
